language: "node_js"
node_js:
  - "9"
  - "8"
  - "6"

before_install:
  - "npm install coveralls"

script:
  - "commitlint-travis"
  - "npm run lint"
  - "npm run test-travis"
  - "cat ./reports/coverage/lcov.info | ./node_modules/.bin/coveralls"

sudo: false
